### ISSUE TITLE
Overhead of Secrets ?

### ISSUE THREAD

**Issue by yoanlcq** [PistonDevelopers/dyon#465]
Greetings, 

This is not a critical issue since said "overhead" is likely to be negligible, and Dyon is a scripting language anyway, so practical affordances are likely to matter most.

The thing is, as a reader of the Dyon tutorial, I couldn't help but raise an eyebrow at the concept of "Secrets", for these reasons : 
- I'm hardly convinced by the use cases shown in the tutorial (i.e If I want to pair a `bool` with a `string`, I'd rather use a tuple or struct), **but** those demonstrated in [#266](https://github.com/PistonDevelopers/dyon/issues/266) actually look cool and practical;
- There has got to be some overhead, somewhere, if any `bool` or `f64` is implicitly able to store extra info such as strings. Could it be that `bool`s are actually 32-bit integers which point to string memory if they're not `false` ? (I don't actually think so, but it's the kind of question that comes to mind).

IMO the tutorial could benefit from mentioning better, more concrete use cases for Secrets, and explaining how they're implemented under the hood.

**Comment by bvssvni** [comment]
You're right. The tutorial does not explain secrets at all.

Since Dyon supports 4D vectors, the size of the `Variable` enum is quite large. This means better performance for 4D vectors but slower performance for `bool` and `f64`. Dyon is designed for game development so this is a reasonable trade-off. The overhead from executing extra instructions for secrets is not that large because of good cache locality.

The extra space can be used for extra features, and secrets is a very useful one. I got the inspiration from constructive theorem proving. E.g. if you say that a list contains a number less than 2, then there must be an index I can look up in the list to check that this is indeed the case. In mathematics this property is called "constructive" because you can construct the element for which the proposition is true. In constraint programming this is also very useful, because the meaning of a solution is closely connected to all constraints in the puzzle being solved.

The cool thing about secrets is that you can write code using compositions of `any`/`all`/`min`/`max` loops that determine some truth value, and Dyon will automatically provide an array of indices that corresponds to the shape of the code.

Another cool thing is that`any`/`all` are similar expressions in first-order logic, so you can use Dyon as a nice scripting language for theorem proving.

**Comment by yoanlcq** [comment]
I see ! Thanks for the explanation.

I believe I "get" the usefulness of secrets now, but I suspect some people (including me) might see them as kind of "backwards from reality" in that, usually, we rather reduce the results of queries into a bool, and not the other way around (that is, extracting results from a bool like secrets do).  

I'm not suggesting that secrets are a bad idea (on the contrary, they are a nice innovation), but rather suggesting that the tutorial ought to mention something like "Well it might be backwards from what you're used to, but it's fine because it's implemented under the hood as X and you'll like it because of Y", not unlike what you described here.

Guess we could say... It boils down to \*explaining the why\* of Secrets in the tutorial. 🕶

**Comment by bvssvni** [comment]
Yes, the tutorial needs to explain this better.

**Comment by bvssvni** [comment]
Closing because the tutorial is fixed http://www.piston.rs/dyon-tutorial/secrets.html
