### ISSUE TITLE
How to push to an array inside object?

### ISSUE THREAD

**Issue by rickyhan** [PistonDevelopers/dyon#565]
```
    a := {b: []}
    push(mut a.b, 1)
    println(a)
```

This returns an error saying expected reference to array.

**Comment by bvssvni** [comment]
This is a limitation of Dyon's memory model.

Dyon uses copy-on-write, so when you modify `b` it creates a new copy different from the one `a` has.

However, if you structure your programs such that this is efficient, then it's later easier to e.g. use multi-threads. So, just because you can't do this thing doesn't necessary mean that it's that bad in practice.

**Comment by rickyhan** [comment]
cloning drastically impacts performance.

I ended up using array indexing (50x speedup).
